### ISSUE TITLE
People search and content search most recent results are months old

### ISSUE THREAD

**Issue by desoter** [ente-io/photos-desktop#314]
On linux appimage, I have enabled both ML and Face recognition.

After full sync and indexes update, the most recent results shown for people and content (e.g. "cat", "car") are of 1st November.
Instead, Magic search provide updated results.

In the log I find this error every time a new photo is uploaded:
`[2024-01-20T17:30:57+01:00] [info]  [MLService] Got file:  38499647
[2024-01-20T17:30:57+01:00] [info]  loaded blazeFaceModel:  webgl
[2024-01-20T17:30:57+01:00] [info]  error: Error Failed to link vertex and fragment shaders. 
                msg: ml detection failed 
                Error: Failed to link vertex and fragment shaders.
    at Object.g (ente://app/_next/static/chunks/6315-3f2a78a62dcf473c.js:10205:2254)
    at l.createProgram (ente://app/_next/static/chunks/6315-3f2a78a62dcf473c.js:2429:5204)
    at Object.i (ente://app/_next/static/chunks/6315-3f2a78a62dcf473c.js:2444:528)
    at ente://app/_next/static/chunks/eea4aac7-cbf6764279272ffb.js:16:12541
    at w.getAndSaveBinary (ente://app/_next/static/chunks/eea4aac7-cbf6764279272ffb.js:16:13294)
    at w.runWebGLProgram (ente://app/_next/static/chunks/eea4aac7-cbf6764279272ffb.js:16:12516)
    at w.uploadToGPU (ente://app/_next/static/chunks/eea4aac7-cbf6764279272ffb.js:16:14838)
    at ente://app/_next/static/chunks/eea4aac7-cbf6764279272ffb.js:16:12078
    at Array.map (<anonymous>)
    at w.runWebGLProgram (ente://app/_next/static/chunks/eea4aac7-cbf6764279272ffb.js:16:11620)`

Attaching log of latest app start, thanks!

[ente.log](https://github.com/ente-io/photos-desktop/files/13998657/ente.log)

**Comment by vishnukvmd** [comment]
Hey, thanks for sharing the logs!

We're re-working the face detection piece at the moment, to incorporate user feedback and to sync the derived indexes (end-to-end encrypted). This is a major overhaul, and I'll bump up this thread once that release is out to confirm that this issue has been fixed. Will keep this issue open until then.

**Comment by desoter** [comment]
Great, thanks!
